"""
retrain_models.py

Re-train 3 LightGBM models compatible with the currently installed LightGBM version,
using the pre-computed feature CSVs in output-dataset/ that were generated by the
original lgb1/lgb2/lgb3 notebooks.

Usage:
    python retrain_models.py

Output:
    models/lgb1.pkl  (overwrites old broken stub)
    models/lgb2.pkl
    models/lgb3.pkl

Training time: ~5-10 min on CPU (using a subset of the data for speed).
"""

import os
import sys
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import lightgbm as lgb

# ─────────────────────────────
# Paths
# ─────────────────────────────
DATA_DIR = "home-credit-default-risk"
OUTPUT_DIR = "home-credit-default-risk/output-dataset"
MODEL_DIR = "models"
os.makedirs(MODEL_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# Load and merge all pre-computed feature CSVs with the application data
# ─────────────────────────────────────────────────────────────────────────────
def load_data():
    print("Loading application_train.csv...")
    app = pd.read_csv(os.path.join(DATA_DIR, "application_train.csv"))
    y = app["TARGET"]
    app = app.drop(columns=["TARGET"])

    # Simple label encode all object columns
    for col in app.select_dtypes(include="object").columns:
        app[col], _ = pd.factorize(app[col])

    print(f"  application shape: {app.shape}")

    # Merge all pre-computed score CSVs (train splits only)
    csv_files = [
        ("buro_score.csv",         "SK_ID_CURR"),
        ("prev_score.csv",         "SK_ID_CURR"),
        ("agg_buro_score.csv",     "SK_ID_CURR"),
        ("agg_prev_score.csv",     "SK_ID_CURR"),
        ("agg_month_score.csv",    "SK_ID_CURR"),
        ("bubl_score_train.csv",   "SK_ID_CURR"),
        ("cc_score_train.csv",     "SK_ID_CURR"),
        ("inst_score_train.csv",   "SK_ID_CURR"),
        ("pos_score_train.csv",    "SK_ID_CURR"),
        ("house_ex.csv",           "SK_ID_CURR"),
        ("train_doc_score.csv",    "SK_ID_CURR"),
        ("train_house_score.csv",  "SK_ID_CURR"),
    ]

    merged = app.copy()
    for fname, key in csv_files:
        fpath = os.path.join(OUTPUT_DIR, fname)
        if not os.path.exists(fpath):
            print(f"  Skipping missing: {fname}")
            continue
        try:
            df = pd.read_csv(fpath, encoding='latin1', on_bad_lines='skip', engine='python')
            # Avoid duplicate columns (except the merge key)
            dup_cols = [c for c in df.columns if c in merged.columns and c != key]
            df = df.drop(columns=dup_cols, errors="ignore")
            merged = merged.merge(df, on=key, how="left")
            print(f"  Merged {fname}: shape now {merged.shape}")
        except Exception as e:
            print(f"  Failed to load {fname}: {e}")
            continue

    merged = merged.set_index("SK_ID_CURR")
    merged = merged.replace([np.inf, -np.inf], np.nan)

    # Drop object/string columns that slipped through
    obj_cols = merged.select_dtypes(include="object").columns
    if len(obj_cols) > 0:
        merged = merged.drop(columns=obj_cols)

    print(f"\nFinal merged shape: {merged.shape}")
    return merged, y

# ─────────────────────────────────────────────────────────────────────────────
# Train one LightGBM model with given random seed (for diversity between lgb1/2/3)
# ─────────────────────────────────────────────────────────────────────────────
def train_single_lgb(X_train, X_val, y_train, y_val, seed, num_rounds=500):
    params = {
        "objective": "binary",
        "metric": "auc",
        "learning_rate": 0.05,
        "num_leaves": 48,
        "max_depth": -1,
        "min_child_samples": 30,
        "feature_fraction": 0.8,
        "bagging_fraction": 0.8,
        "bagging_freq": 5,
        "reg_alpha": 0.1,
        "reg_lambda": 0.1,
        "random_state": seed,
        "verbose": -1,
        "n_jobs": -1,
    }
    model = lgb.LGBMClassifier(**params, n_estimators=num_rounds)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(50, verbose=False), lgb.log_evaluation(100)],
    )
    val_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, val_pred)
    print(f"  Val AUC: {auc:.4f}")
    return model


if __name__ == "__main__":
    X, y = load_data()

    # Align y index to X index safely
    y.index = X.index

    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.15, random_state=42, stratify=y
    )
    print(f"\nTrain: {X_train.shape}  |  Val: {X_val.shape}")

    for i, seed in enumerate([42, 137, 99], start=1):
        print(f"\n{'='*50}")
        print(f"Training lgb{i} (seed={seed})...")
        model = train_single_lgb(X_train, X_val, y_train, y_val, seed)
        out_path = os.path.join(MODEL_DIR, f"lgb{i}_booster.txt")
        model.booster_.save_model(out_path)
        print(f"  Saved to {out_path}")

    print("\n✓ All 3 models retrained and saved as booster .txt files/")
    print("  Run the pipeline with: python main.py")
