"""
CreditLens A1 — Local Document Parser.

# LOCAL_SUB: This replaces AWS Textract Analyze Lending API.
# Production: Replace with TextractService using boto3.client('textract')

Parses PDF documents using PyMuPDF (fitz) to extract structured fields.
Designed to work with the standardized Vietnamese document formats
generated by data/mock/generate_mock_data.py.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF

logger = logging.getLogger(__name__)


class LocalDocumentParser:
    """Local PDF parser using PyMuPDF.

    # LOCAL_SUB: Replace with TextractService for AWS deployment.
    # See LOCAL_SUBSTITUTIONS.md for migration guide.

    Parses Vietnamese PDF documents to extract key-value fields:
    - CCCD → identity, gender, DOB, addresses
    - Hợp đồng lao động → employer, salary, position, start date
    - Sổ hộ khẩu → family members, marital status
    - Thẩm định nhà ở → housing quality, area, construction year
    - Đơn vay → loan amount, term, purpose
    """

    # Field pattern: "Label:  Value" or "Label:Value"
    FIELD_RE = re.compile(r"^(.+?):\s+(.+)$", re.MULTILINE)

    def extract_document(self, pdf_path: str | Path, doc_type: str = "auto") -> dict[str, Any]:
        """Extract fields from a PDF document.

        Args:
            pdf_path: Path to PDF file.
            doc_type: Document type: "cccd", "employment", "household",
                      "housing", "loan_application", "auto".

        Returns:
            Dict with: fields, confidence, doc_type, raw_text
        """
        pdf_path = Path(pdf_path)
        if not pdf_path.exists():
            logger.warning(f"PDF not found: {pdf_path}")
            return {"doc_type": doc_type, "fields": {}, "confidence": {}, "raw_text": ""}

        # Extract text from all pages
        doc = fitz.open(str(pdf_path))
        full_text = "\n".join(page.get_text() for page in doc)
        doc.close()

        logger.info(f"Extracted {len(full_text)} chars from {pdf_path.name}")

        # Auto-detect doc type
        if doc_type == "auto":
            doc_type = self._detect_doc_type(full_text, pdf_path.name)

        # Parse based on doc type
        parsers = {
            "cccd": self._parse_cccd,
            "employment": self._parse_employment,
            "household": self._parse_household,
            "housing": self._parse_housing,
            "loan_application": self._parse_loan_application,
        }

        parser = parsers.get(doc_type, self._parse_generic)
        result = parser(full_text)
        result["doc_type"] = doc_type
        result["raw_text"] = full_text

        return result

    def _detect_doc_type(self, text: str, filename: str) -> str:
        """Auto-detect document type from text content or filename."""
        text_lower = text.lower()
        fname_lower = filename.lower()

        # Support both ASCII and Vietnamese diacritics
        if "cccd" in fname_lower or "căn cước" in text_lower or "can cuoc" in text_lower or "cmnd" in fname_lower:
            return "cccd"
        if "hợp đồng lao động" in text_lower or "hop dong lao dong" in text_lower or "hop_dong" in fname_lower:
            return "employment"
        if "hộ khẩu" in text_lower or "ho khau" in text_lower or "ho_khau" in fname_lower:
            return "household"
        if "thẩm định" in text_lower or "tham dinh" in text_lower or "nhà ở" in text_lower or "nha o" in text_lower or "tham_dinh" in fname_lower:
            return "housing"
        if "đơn vay" in text_lower or "don vay" in text_lower or "đề nghị vay" in text_lower or "de nghi vay" in text_lower or "don_vay" in fname_lower:
            return "loan_application"
        return "unknown"

    def _extract_key_value(self, text: str) -> dict[str, str]:
        """Extract all key:value pairs from text."""
        fields = {}
        for match in self.FIELD_RE.finditer(text):
            key = match.group(1).strip()
            value = match.group(2).strip()
            fields[key] = value
        return fields

    def _parse_cccd(self, text: str) -> dict[str, Any]:
        """Parse CCCD/CMND document."""
        kv = self._extract_key_value(text)
        fields = {}
        confidence = {}

        # Map extracted fields — support both ASCII and Vietnamese diacritics
        field_map = {
            # Vietnamese diacritics versions
            "Họ và tên": ("full_name", 0.97),
            "Số CCCD": ("id_number", 0.98),
            "Ngày sinh": ("date_of_birth", 0.95),
            "Giới tính": ("gender", 0.99),
            "Quốc tịch": ("nationality", 0.95),
            "Nơi thường trú": ("permanent_address", 0.90),
            "Địa chỉ thường trú": ("permanent_address", 0.90),
            "Ngày cấp": ("id_issue_date", 0.95),
            "Nơi cấp": ("id_issue_place", 0.92),
            "Ngày đăng ký": ("registration_date", 0.88),
            "Địa chỉ hiện tại": ("current_address", 0.88),
            "Địa chỉ làm việc": ("work_address", 0.85),
            "CMND cũ": ("old_id_number", 0.90),
            # ASCII fallbacks
            "Ho va ten": ("full_name", 0.97),
            "So CCCD": ("id_number", 0.98),
            "Ngay sinh": ("date_of_birth", 0.95),
            "Gioi tinh": ("gender", 0.99),
            "Quoc tich": ("nationality", 0.95),
            "Noi thuong tru": ("permanent_address", 0.90),
            "Dia chi thuong tru": ("permanent_address", 0.90),
            "Ngay cap": ("id_issue_date", 0.95),
            "Noi cap": ("id_issue_place", 0.92),
            "Ngay dang ky": ("registration_date", 0.88),
            "Dia chi hien tai": ("current_address", 0.88),
            "Dia chi lam viec": ("work_address", 0.85),
            "CMND cu": ("old_id_number", 0.90),
        }

        for kv_key, (field_name, conf) in field_map.items():
            if kv_key in kv:
                fields[field_name] = kv[kv_key]
                confidence[field_name] = conf

        # Document flags — check what documents were mentioned/submitted
        fields["identity_verified"] = bool(fields.get("id_number"))
        confidence["identity_verified"] = 0.95 if fields.get("identity_verified") else 0.0

        return {"fields": fields, "confidence": confidence}

    def _parse_employment(self, text: str) -> dict[str, Any]:
        """Parse Labor Contract PDF."""
        kv = self._extract_key_value(text)
        fields = {}
        confidence = {}

        field_map = {
            # Vietnamese diacritics versions
            "Tên doanh nghiệp": ("employer_name", 0.94),
            "Địa chỉ": ("employer_address", 0.90),
            "Mã số thuế": ("employer_tax_id", 0.95),
            "Điện thoại": ("employer_phone", 0.92),
            "Họ và tên": ("full_name", 0.95),
            "Chức danh": ("position", 0.90),
            "Phòng ban": ("department", 0.88),
            "Ngày bắt đầu": ("employment_start_date", 0.92),
            "Loại hợp đồng": ("contract_type", 0.95),
            "Lương cơ bản": ("base_salary", 0.90),
            "Phụ cấp": ("allowance", 0.88),
            "Tổng thu nhập": ("total_monthly_income", 0.92),
            "Thu nhập năm": ("annual_income", 0.90),
            "Hình thức trả": ("payment_method", 0.90),
            "Ngân hàng nhận lương": ("salary_bank", 0.88),
            "Số tài khoản": ("bank_account", 0.85),
            "Số BHXH": ("social_insurance_number", 0.90),
            # ASCII fallbacks
            "Ten doanh nghiep": ("employer_name", 0.94),
            "Dia chi": ("employer_address", 0.90),
            "Ma so thue": ("employer_tax_id", 0.95),
            "Dien thoai": ("employer_phone", 0.92),
            "Ho va ten": ("full_name", 0.95),
            "Chuc danh": ("position", 0.90),
            "Phong ban": ("department", 0.88),
            "Ngay bat dau": ("employment_start_date", 0.92),
            "Loai hop dong": ("contract_type", 0.95),
            "Luong co ban": ("base_salary", 0.90),
            "Phu cap": ("allowance", 0.88),
            "Tong thu nhap": ("total_monthly_income", 0.92),
            "Thu nhap nam": ("annual_income", 0.90),
            "Hinh thuc tra": ("payment_method", 0.90),
            "Ngan hang nhan luong": ("salary_bank", 0.88),
            "So tai khoan": ("bank_account", 0.85),
            "So BHXH": ("social_insurance_number", 0.90),
        }

        for kv_key, (field_name, conf) in field_map.items():
            if kv_key in kv:
                fields[field_name] = kv[kv_key]
                confidence[field_name] = conf

        # Parse salary amounts
        for salary_field in ["base_salary", "total_monthly_income", "annual_income", "allowance"]:
            if salary_field in fields:
                val = fields[salary_field]
                # Extract numeric value from "35,000,000 VND/tháng"
                nums = re.findall(r"[\d,]+", str(val).replace(".", ""))
                if nums:
                    fields[salary_field] = int(nums[0].replace(",", ""))

        return {"fields": fields, "confidence": confidence}

    def _parse_household(self, text: str) -> dict[str, Any]:
        """Parse Sổ hộ khẩu PDF."""
        kv = self._extract_key_value(text)
        fields = {}
        confidence = {}

        field_map = {
            # Vietnamese diacritics versions
            "Họ và tên chủ hộ": ("head_of_household", 0.95),
            "Tổng số nhân khẩu": ("family_members_count", 0.92),
            "Số con": ("children_count", 0.90),
            "Tình trạng hôn nhân chủ hộ": ("marital_status", 0.92),
            "Tình trạng hôn nhân": ("marital_status", 0.92),
            # ASCII fallbacks
            "Ho va ten chu ho": ("head_of_household", 0.95),
            "Tong so nhan khau": ("family_members_count", 0.92),
            "So con": ("children_count", 0.90),
            "Tinh trang hon nhan chu ho": ("marital_status", 0.92),
            "Tinh trang hon nhan": ("marital_status", 0.92),
        }

        for kv_key, (field_name, conf) in field_map.items():
            if kv_key in kv:
                fields[field_name] = kv[kv_key]
                confidence[field_name] = conf

        # Parse numeric fields
        if "family_members_count" in fields:
            nums = re.findall(r"\d+", str(fields["family_members_count"]))
            if nums:
                fields["family_members_count"] = int(nums[0])

        if "children_count" in fields:
            nums = re.findall(r"\d+", str(fields["children_count"]))
            if nums:
                fields["children_count"] = int(nums[0])

        # Count family members with "Con" relationship
        con_count = len(re.findall(
            r"Quan hệ với chủ hộ:\s*Con|Quan he voi chu ho:\s*Con",
            text, re.IGNORECASE
        ))
        if con_count > 0 and "children_count" not in fields:
            fields["children_count"] = con_count
            confidence["children_count"] = 0.85

        return {"fields": fields, "confidence": confidence}

    def _parse_housing(self, text: str) -> dict[str, Any]:
        """Parse Housing Survey / Collateral PDF."""
        kv = self._extract_key_value(text)
        fields = {}
        confidence = {}

        field_map = {
            # Vietnamese diacritics versions
            "Loại hình nhà ở": ("housing_type", 0.92),
            "Diện tích sử dụng": ("living_area", 0.90),
            "Diện tích": ("living_area", 0.90),
            "Năm xây dựng": ("year_built", 0.88),
            "Số tầng tòa nhà": ("max_floors", 0.90),
            "Tầng căn hộ": ("floor_number", 0.90),
            "Có thang máy": ("has_elevator", 0.95),
            "Vật liệu tường": ("wall_material", 0.90),
            "Tình trạng khẩn cấp": ("emergency_state", 0.92),
            "Mật độ dân số (tương đối)": ("region_population_relative", 0.85),
            "Xếp hạng khu vực": ("region_rating", 0.88),
            "Xếp hạng khu vực (TP)": ("region_rating_w_city", 0.88),
            "Chất lượng căn hộ (1-10)": ("apartment_quality", 0.85),
            "Diện tích tầng hầm": ("basement_area", 0.82),
            "Diện tích đất (toàn khu)": ("land_area", 0.85),
            "Diện tích sinh hoạt": ("living_area_detail", 0.88),
            "Diện tích chung": ("common_area", 0.82),
            "Số lối vào": ("entrances", 0.88),
            "Giá trị ước tính": ("estimated_value", 0.85),
            "Địa chỉ BĐS": ("property_address", 0.90),
            "Đăng ký cùng vùng sống": ("reg_live_same_region", 0.88),
            "Đăng ký cùng TP làm việc": ("reg_work_same_city", 0.88),
            "Sống cùng vùng làm việc": ("live_work_same_region", 0.88),
            # ASCII fallbacks
            "Loai hinh nha o": ("housing_type", 0.92),
            "Dien tich su dung": ("living_area", 0.90),
            "Dien tich": ("living_area", 0.90),
            "Nam xay dung": ("year_built", 0.88),
            "So tang toa nha": ("max_floors", 0.90),
            "Tang can ho": ("floor_number", 0.90),
            "Co thang may": ("has_elevator", 0.95),
            "Vat lieu tuong": ("wall_material", 0.90),
            "Tinh trang khan cap": ("emergency_state", 0.92),
            "Mat do dan so (tuong doi)": ("region_population_relative", 0.85),
            "Xep hang khu vuc": ("region_rating", 0.88),
            "Xep hang khu vuc (TP)": ("region_rating_w_city", 0.88),
            "Chat luong can ho (1-10)": ("apartment_quality", 0.85),
            "Dien tich tang ham": ("basement_area", 0.82),
            "Dien tich dat (toan khu)": ("land_area", 0.85),
            "Dien tich sinh hoat": ("living_area_detail", 0.88),
            "Dien tich chung": ("common_area", 0.82),
            "So loi vao": ("entrances", 0.88),
            "Gia tri uoc tinh": ("estimated_value", 0.85),
            "Dia chi BDS": ("property_address", 0.90),
            "Dang ky cung vung song": ("reg_live_same_region", 0.88),
            "Dang ky cung TP lam viec": ("reg_work_same_city", 0.88),
            "Song cung vung lam viec": ("live_work_same_region", 0.88),
        }

        for kv_key, (field_name, conf) in field_map.items():
            if kv_key in kv:
                fields[field_name] = kv[kv_key]
                confidence[field_name] = conf

        # Parse numeric fields
        for nf in ["living_area", "year_built", "max_floors", "floor_number"]:
            if nf in fields:
                nums = re.findall(r"[\d.]+", str(fields[nf]))
                if nums:
                    fields[nf] = float(nums[0]) if "." in nums[0] else int(nums[0])

        if "region_population_relative" in fields:
            nums = re.findall(r"[\d.]+", str(fields["region_population_relative"]))
            if nums:
                fields["region_population_relative"] = float(nums[0])

        if "region_rating" in fields:
            nums = re.findall(r"\d+", str(fields["region_rating"]))
            if nums:
                fields["region_rating"] = int(nums[0])

        if "region_rating_w_city" in fields:
            nums = re.findall(r"\d+", str(fields["region_rating_w_city"]))
            if nums:
                fields["region_rating_w_city"] = int(nums[0])

        return {"fields": fields, "confidence": confidence}

    def _parse_loan_application(self, text: str) -> dict[str, Any]:
        """Parse Loan Application PDF."""
        kv = self._extract_key_value(text)
        fields = {}
        confidence = {}

        field_map = {
            # Vietnamese diacritics versions
            "Loại hợp đồng": ("contract_type", 0.95),
            "Số tiền vay": ("loan_amount", 0.95),
            "Kỳ hạn": ("loan_term_months", 0.95),
            "Trả hàng tháng (dự kiến)": ("monthly_payment", 0.92),
            "Giá trị hàng hóa": ("goods_price", 0.92),
            "Mục đích": ("loan_purpose", 0.90),
            "Trình độ học vấn": ("education_type", 0.90),
            "Tình trạng hôn nhân": ("marital_status", 0.92),
            "Có xe ô tô": ("has_car", 0.95),
            "Tuổi xe (năm)": ("car_age", 0.90),
            "Có bất động sản": ("has_realty", 0.95),
            "Người đồng hành": ("type_suite", 0.88),
            "Số di động liên lạc được": ("flag_cont_mobile", 0.95),
            "Số điện thoại bàn": ("flag_phone", 0.90),
            "Email": ("flag_email", 0.90),
            "Ngày đổi SĐT gần nhất": ("days_last_phone_change_info", 0.85),
            "SĐT": ("phone_number", 0.95),
            # ASCII fallbacks
            "Loai hop dong": ("contract_type", 0.95),
            "So tien vay": ("loan_amount", 0.95),
            "Ky han": ("loan_term_months", 0.95),
            "Tra hang thang (du kien)": ("monthly_payment", 0.92),
            "Gia tri hang hoa": ("goods_price", 0.92),
            "Muc dich": ("loan_purpose", 0.90),
            "Trinh do hoc van": ("education_type", 0.90),
            "Tinh trang hon nhan": ("marital_status", 0.92),
            "Co xe o to": ("has_car", 0.95),
            "Tuoi xe (nam)": ("car_age", 0.90),
            "Co bat dong san": ("has_realty", 0.95),
            "Nguoi dong hanh": ("type_suite", 0.88),
            "So di dong lien lac duoc": ("flag_cont_mobile", 0.95),
            "So dien thoai ban": ("flag_phone", 0.90),
            "Ngay doi SDT gan nhat": ("days_last_phone_change_info", 0.85),
            "SDT": ("phone_number", 0.95),
        }

        for kv_key, (field_name, conf) in field_map.items():
            if kv_key in kv:
                fields[field_name] = kv[kv_key]
                confidence[field_name] = conf

        # Parse amounts
        for amt_field in ["loan_amount", "monthly_payment", "goods_price"]:
            if amt_field in fields:
                nums = re.findall(r"[\d,]+", str(fields[amt_field]).replace(".", ""))
                if nums:
                    fields[amt_field] = int(nums[0].replace(",", ""))

        # Parse term
        if "loan_term_months" in fields:
            nums = re.findall(r"\d+", str(fields["loan_term_months"]))
            if nums:
                fields["loan_term_months"] = int(nums[0])

        # Parse car age
        if "car_age" in fields:
            nums = re.findall(r"\d+", str(fields["car_age"]))
            if nums:
                fields["car_age"] = int(nums[0])

        # Parse binary yes/no (support both ASCII and Vietnamese)
        for bin_field in ["has_car", "has_realty", "flag_cont_mobile", "flag_phone", "flag_email"]:
            if bin_field in fields:
                val = str(fields[bin_field]).lower()
                fields[bin_field] = 1 if val in ("có", "co", "yes", "1", "true") else 0

        return {"fields": fields, "confidence": confidence}

    def _parse_generic(self, text: str) -> dict[str, Any]:
        """Fallback: extract all key:value pairs."""
        kv = self._extract_key_value(text)
        confidence = {k: 0.70 for k in kv}
        return {"fields": kv, "confidence": confidence}
